### PR TITLE
fix: Responsive Design Issues for Improved Cross-Device Compatibility

### LINKED ISSUE #51: [FEATURE] Make oss.gg fully responsive
### Issue Summary

I just exploring through mobile and found that oss.gg is not mobile user friendly. 

https://github.com/formbricks/oss.gg/assets/77881638/eafc6f8e-5d0c-4563-a6f0-231c05581191

### Steps to Reproduce

1. Open in mobile device 

### Expected behavior

All components should proper set so user can check their update from mobile device also

### Other information

_No response_

### Screenshots

_No response_

### Desktop (please complete the following information)

```markdown
- OS: Android
```

### PR DESCRIPTION
**Pull request by nik132-eng**
## What does this PR do?

Make design mobile-friendly

Fixes #51 

------------------------------------------------------------------------------------------------------------
Before
------------------------------------------------------------------------------------------------------------
image

image

image

------------------------------------------------------------------------------------------------------------
After
------------------------------------------------------------------------------------------------------------

image

image

image

image

## How should this be tested?

- use in mobile device

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at oss.gg](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by nik132-eng** [comment]
@mattinannt, One more page needs to be checked in responsiveness which is in the repository

image

in the local environment I filled out the dummy project but not immediately added. just asking in the future is that automated?

image

**Comment by nik132-eng** [comment]
Issue tab
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------

image

image

image

image

**Comment by jobenjada** [comment]
Hey @nik132-eng - thanks for your start.

This is quite a comprehensive issue giving 250 Points, so please make sure the complete app is properly responsive :)

Here are few points:

1. Add a hamburger menu on mobile
image

------------

2. Headlines too big
image

--------

3. Add hamburger menu to dashboard. Right now it impossible to navigate:
image

--------

4. Reorganize the card content so its stacked on top of each other (flex-col)
image

------

5. Decrease spacing between items:


-------

Please go through all the screens and make sure the complete app is responsive :))

Thanks!!

**Review by jobenjada — CHANGES_REQUESTED** [review]
see comment

**Comment by nikdev10** [comment]
@jobenjada I made changes

**Review by jobenjada — APPROVED** [review]

**Pull request merged**
