### PR TITLE
feat: delete account UI

### PR DESCRIPTION
**Pull request by Chigala**
## What does this PR do?
add the delete account UI

Fixes # (issue)
#32 

Screenshot 2024-03-19 at 20 18 00
Screenshot 2024-03-19 at 20 18 18

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at oss.gg](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
hey @Chigala 

wanna also add the delete functionality? 

we are working with the same tech stack with Formbricks, you can have a look at how we did it here:

https://github.com/formbricks/formbricks/blob/main/apps/web/app/(app)/environments/%5BenvironmentId%5D/settings/profile/actions.ts

**Comment by Chigala** [comment]
@jobenjada I think this is ready for review. Tell me what you think about the tables I'm deleting.

**Pull request merged**
