### PR TITLE
feat: Get LEVEL Creation to work 

### PR DESCRIPTION
**Pull request by manish-singh-bisht**
## What does this PR do?

fixes: #72 

video1: showing visibility of levels 
[Screencast from 15-05-24 02:25:33 AM IST.webm](https://github.com/formbricks/oss.gg/assets/114493480/42c3d95c-6316-4757-ab0b-0b61d87364a7)

video2: showing functionality   
[Screencast from 15-05-24 02:16:23 AM IST.webm](https://github.com/formbricks/oss.gg/assets/114493480/999569ff-3b77-43ed-8da7-1625326b843e)

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [x] Read [How we Code at oss.gg](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by manish-singh-bisht** [comment]
things remaining in this pr for it to be complete:
(These are not solved because I don't have S3 access token and other required envs related to s3)

1) testing/correcting/refactoring the icon upload code.
2)add a fallback icon,when no icon,currently displaying a div with "fallback content".
3).testing update functionality with icon. (the update level functionality, without image, is working correct)

(functions related to icon upload has not been touched , maybe commented,may require to amend/remove them accordingly.)
+
any other related to icon.

i have created a draft pr, solving majority issues. the above ones are remaining and in order to solve them you need to have envs related to aws S3.

Thank you

**Comment by jobenjada** [comment]
Hey @manish-singh-bisht 

Thanks a lot for shipping this and sorry for the delayed review.

Most of the comments are related to the levels not being visible to the users. Pls recall that the levels are derived from the current points a user has. This should make it fairly easy to display both the current score and corresponding level / progress bar.

Please make sure to build reusable components to which you can pass the levels object and the current point score. The component then decides what to display to each user. Does that make sense?

Here the different views we need to see levels:

-------

1. Add Level info to dashboard

from 

image

to

image

See here

https://www.figma.com/file/usCYaOpv13zMpvjEVc5z0Z/oss.gg-web-app?type=design&node-id=1%3A208&mode=design&t=VtKKdyMS1yAZfiJu-1

------

2. Add levels tabs and infos to the repository detail page:

image

https://www.figma.com/file/usCYaOpv13zMpvjEVc5z0Z/oss.gg-web-app?type=design&node-id=6%3A673&mode=design&t=VtKKdyMS1yAZfiJu-1

------

3. Add levels info to the Leaderboard

If a repository has levels, we should display them in the leaderboard. 

image

If there is no user yet in a specific level, display a placeholder text: 

"No player levelled up here yet. Who's gonna be the first?"

-------

4. Open issues list: Add level info

We already pull all the labels from the issues. Find a good approach to compare the attached labels of issues with the label settings of all the levels a repository has. For each issue, display the badges of the levels which are eligible to work on this issue:

image
image

While your own the issue component anyways, please update the styling to match the Figma layout.

-------

5. On the public profile page

Display the corresponding level emblem with the repo logo (in small) underneath the image:

image

image

-------

REVIEW IN PROGRESS

**Comment by manish-singh-bisht** [comment]
@jobenjada  ready for review.

have added video in the description

**Comment by jobenjada** [comment]
Hey @manish-singh-bisht 

thanks a lot for following up, this looks really good :)

Noticed one thing:

1. When you want to create a new level and hit "Save" without having added an image, it removes the form incl. all inputs. Instead, just highlight the field upload field with a red border and keep all values in the form :)

I'll go ahead and merge this regardless, as its a minor tweak which shouldn't block us :)

**Pull request merged**
