### PR TITLE
feat: Post Discord channel message on points earned

### LINKED ISSUE #75: [FEATURE] Discord Notification on Points Awarded
### Is your feature request related to a problem? Please describe.

Currently, we have to manually inform our communtiy, if someone was awarded points.

### Describe the solution you'd like

Automate it using trigger.dev 

Hit up @Chigala if you have any questions on how to do it best :)

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by raysubham**
## What does this PR do?

1. Posts discord channel message whenever someone earns new points

Fixes #75 

https://github.com/formbricks/oss.gg/assets/66999381/b9467d00-0d39-43e5-9689-bd97b3e613e3

## How should this be tested?

- Create a discord bot and install it in the server.
- Get the `bot token` and `channel ID` and add the env variables
- Award points and the discord message should be posted

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at oss.gg](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
Hey!

So i've created and installed the Discord bot. However, when I run this branch, the normal GitHub comment on point award does not work anymore and I get this error:

```
AggregateError: 
    Error: SyntaxError: Unexpected token < in JSON at position 0
        at eval (webpack-internal:///(api)/./lib/github/hooks/issue.ts:342:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 2)
        at async middleware (/Users/johannes/Developer/ossgg/oss.gg/node_modules/.pnpm/@octokit+webhooks@12.1.0/node_modules/@octokit/webhooks/dist-node/index.js:613:5)
    at /Users/johannes/Developer/ossgg/oss.gg/node_modules/.pnpm/@octokit+webhooks@12.1.0/node_modules/@octokit/webhooks/dist-node/index.js:422:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async middleware (/Users/johannes/Developer/ossgg/oss.gg/node_modules/.pnpm/@octokit+webhooks@12.1.0/node_modules/@octokit/webhooks/dist-node/index.js:613:5) {
  event: {
    id: 'c53f5740-0d42-11ef-9469-f7b2f6403416',
    name: 'issue_comment',
    payload: {
      action: 'created',
      issue: [Object],
      comment: [Object],
      repository: [Object],
      sender: [Object],
      installation: [Object]
    }
  },
  errors: [
    Error: SyntaxError: Unexpected token < in JSON at position 0
        at eval (webpack-internal:///(api)/./lib/github/hooks/issue.ts:342:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 2)
        at async middleware (/Users/johannes/Developer/ossgg/oss.gg/node_modules/.pnpm/@octokit+webhooks@12.1.0/node_modules/@octokit/webhooks/dist-node/index.js:613:5) {
      event: [Object]
    }
  ]
}

```

I'm not very familiar with Trigger but see that you made some changes in the PR which likely cause this (since it doesnt happen on main).

Can you walk me through how I have to set it up correctly? 🤓 

Thanks! :)

**Comment by raysubham** [comment]
> Hey!
> 
> So i've created and installed the Discord bot. However, when I run this branch, the normal GitHub comment on point award does not work anymore and I get this error:
> 
> ```
> AggregateError: 
>     Error: SyntaxError: Unexpected token < in JSON at position 0
>         at eval (webpack-internal:///(api)/./lib/github/hooks/issue.ts:342:19)
>         at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>         at async Promise.all (index 2)
>         at async middleware (/Users/johannes/Developer/ossgg/oss.gg/node_modules/.pnpm/@octokit+webhooks@12.1.0/node_modules/@octokit/webhooks/dist-node/index.js:613:5)
>     at /Users/johannes/Developer/ossgg/oss.gg/node_modules/.pnpm/@octokit+webhooks@12.1.0/node_modules/@octokit/webhooks/dist-node/index.js:422:19
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async middleware (/Users/johannes/Developer/ossgg/oss.gg/node_modules/.pnpm/@octokit+webhooks@12.1.0/node_modules/@octokit/webhooks/dist-node/index.js:613:5) {
>   event: {
>     id: 'c53f5740-0d42-11ef-9469-f7b2f6403416',
>     name: 'issue_comment',
>     payload: {
>       action: 'created',
>       issue: [Object],
>       comment: [Object],
>       repository: [Object],
>       sender: [Object],
>       installation: [Object]
>     }
>   },
>   errors: [
>     Error: SyntaxError: Unexpected token < in JSON at position 0
>         at eval (webpack-internal:///(api)/./lib/github/hooks/issue.ts:342:19)
>         at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>         at async Promise.all (index 2)
>         at async middleware (/Users/johannes/Developer/ossgg/oss.gg/node_modules/.pnpm/@octokit+webhooks@12.1.0/node_modules/@octokit/webhooks/dist-node/index.js:613:5) {
>       event: [Object]
>     }
>   ]
> }
> ```
> 
> I'm not very familiar with Trigger but see that you made some changes in the PR which likely cause this (since it doesnt happen on main).
> 
> Can you walk me through how I have to set it up correctly? 🤓
> 
> Thanks! :)

Let me check the console error and get back to you.

**Comment by raysubham** [comment]
@jobenjada I checked on my local. Discord messages works perfectly. There are no errors for me. Here are the steps that you need to follow:

1. Install the discord bot on the server & add the `bot token` in the env variables.
2. Go to `settings -> advanced` and toggle on `developer mode` in discord. Now you can right click on any channel & copy the `channel id`. Add this id in the env variable.
3. To setup trigger.dev locally, you can follow this guide: https://trigger.dev/docs/documentation/quickstarts/nextjs This has all the steps mentioned. Trigger.dev cli will add a id in package.json ` "endpointId": "some-value"` Please add this id in the `id` field of `trigger.ts` file.
> Note: trigger.dev cli adds a lot of values and boilerplate files on initial installation. We should discard them and not commit them to git.

Let me know if you still face issues while installing.

**Pull request merged**
